### ISSUE TITLE
add methods for mapping collection to inner elements

### ISSUE THREAD

**Issue by alex-popov-tech** [KnowledgeExpert/selenidejs#118]
add something like

collection.all('//div') => finds all div's in each element
collection.map('//div') => find first div in each element, fail if can't find

**Comment by yashaka** [comment]
as discussed in a separate private chat...
let's move from 

```
collection.all('.author') // => finds all .author elements in each element (for example a book among books)
collection.map('.author') // => find first .author in each element, fail if can't find
```

to
```
all.collected(element -> element.element(‘.author’))
all.collected(element -> element.all(‘.author’))
```
try to make it possible to reuse our find.* shortcuts to achieve the same correspondingly:

```
all.collected(find.element(‘.author’))
all.collected(find.all(‘.author’))
```


the reason to use collect term instead of map term comes from the following:
- map is low level FP term that does not make much sense from web ui user perspective... 
- if use map - it's hard to keep consistency with the meaning of map from FP
